/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_lenguajes;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import javax.speech.*;
import javax.speech.recognition.*;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.*;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        this.jDialog1.setModal(false);
        this.jDialog1.pack();
        this.jDialog1.setLocationRelativeTo(this);
        this.jDialog1.setVisible(true);
        Image img = Toolkit.getDefaultToolkit().createImage(getClass().getResource("user.png")).getScaledInstance(169, 145, 0);
        lb_foto.setIcon(new ImageIcon(img));
        imagen_principal.setIcon(new ImageIcon(img));
        try {
            recognizer = Central.createRecognizer(new EngineModeDesc(Locale.ROOT));
            recognizer.allocate();
            recognizer.pause();
        } catch (Exception e) {
            System.out.println("Exception en " + e.toString());
            e.printStackTrace();
            System.exit(0);
        }
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(connection);

        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        refresh();
        refrescar_gramatica();
    }
    String connection = "jdbc:sqlserver://localhost:1433;databaseName=Lenguajes;user=innova;password=12345";
    Connection con;
    Escucha a = new Escucha();
    boolean mic_activado = false;
    Recognizer recognizer;
    boolean first = true;
    String path = "user.png";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_username = new javax.swing.JTextField();
        jt_password = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jd_llamada = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jd_agregar = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_telefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_correo = new javax.swing.JTextField();
        lb_foto = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        errores = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_llamadas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_contactos = new javax.swing.JTable();
        imagen_principal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_mensajes = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("User:");
        jDialog1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 73, -1, -1));

        jLabel3.setText("Password:");
        jDialog1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 122, -1, -1));
        jDialog1.getContentPane().add(jt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 93, 177, -1));
        jDialog1.getContentPane().add(jt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 147, 175, -1));

        jButton4.setText("Activar Voz");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jDialog1.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 185, -1, -1));

        jButton6.setText("Log In");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jDialog1.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 185, 87, -1));
        jDialog1.getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 236, 315, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_lenguajes/Blur-1-1024x667.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jDialog1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));

        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton9.setText("Colgar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel6.setText("Nombre de Contacto");

        jLabel7.setText("Tiempo");

        javax.swing.GroupLayout jd_llamadaLayout = new javax.swing.GroupLayout(jd_llamada.getContentPane());
        jd_llamada.getContentPane().setLayout(jd_llamadaLayout);
        jd_llamadaLayout.setHorizontalGroup(
            jd_llamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_llamadaLayout.createSequentialGroup()
                .addGroup(jd_llamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_llamadaLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel6))
                    .addGroup(jd_llamadaLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_llamadaLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_llamadaLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel7)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jd_llamadaLayout.setVerticalGroup(
            jd_llamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_llamadaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jLabel11.setText("Nombre");

        jLabel12.setText("Teléfono");

        jLabel13.setText("Correo");

        lb_foto.setBackground(new java.awt.Color(0, 0, 0));
        lb_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("Seleccionar");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setText("Guardar");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        errores.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jd_agregarLayout = new javax.swing.GroupLayout(jd_agregar.getContentPane());
        jd_agregar.getContentPane().setLayout(jd_agregarLayout);
        jd_agregarLayout.setHorizontalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(1, 1, 1)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addComponent(errores, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_agregarLayout.setVerticalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errores, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_llamadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contacto", "Fecha", "Duracion"
            }
        ));
        jScrollPane2.setViewportView(tabla_llamadas);

        jLabel9.setText("MIC");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro de LLamadas", jPanel1);

        tabla_contactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Correo"
            }
        ));
        jScrollPane1.setViewportView(tabla_contactos);

        imagen_principal.setBackground(new java.awt.Color(0, 0, 0));
        imagen_principal.setText("jLabel1");
        imagen_principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("MIC");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(imagen_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contactos", jPanel2);

        tabla_mensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contacto", "Contenido", "Fecha", "Hora"
            }
        ));
        jScrollPane3.setViewportView(tabla_mensajes);

        jLabel10.setText("MIC");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mensajes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void refresh() {
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select* from Contacto");
            DefaultTableModel m = (DefaultTableModel) tabla_contactos.getModel();
            while (rs.next()) {
                int id = rs.getInt(1);
                String nombre = rs.getString(2);
                String telefono = rs.getString(3);
                String correo = rs.getString(4);
                Object arr[] = {nombre, telefono, correo};
                m.addRow(arr);
            }
            rs = st.executeQuery("select a.Nombre,b.fecha,b.Duracion from dbo.Contacto a inner join dbo.Llamada b on a.ID_contacto=b.ID_contacto");
            DefaultTableModel n = (DefaultTableModel) tabla_llamadas.getModel();
            while (rs.next()) {
                String nombre = rs.getString(1);
                Date fecha = rs.getDate(2);
                int duracion = rs.getInt(3);
                Object arr[] = {nombre, fecha, duracion};
                n.addRow(arr);
            }
            rs = st.executeQuery("select a.Nombre,b.Contenido,(cast(day(b.Fecha)as nvarchar)+'/'+cast(month(b.Fecha)as nvarchar)+'/'+cast(year(b.Fecha)as nvarchar))as fecha,cast(DATEPART([hour], b.Fecha)as nvarchar)+':'+cast(DATEPART([MINUTE], b.Fecha)as nvarchar) as Hora\n"
                    + "from dbo.Contacto a inner join dbo.Mensaje b on a.ID_contacto=b.ID_contacto");
            DefaultTableModel o = (DefaultTableModel) tabla_mensajes.getModel();
            while (rs.next()) {
                String nombre = rs.getString(1);
                String contenido = rs.getString(2);
                String fecha = rs.getString(3);
                String hora = rs.getString(4);
                Object arr[] = {nombre, contenido, fecha, hora};
                o.addRow(arr);
            }
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void refrescar_gramatica() {
        File archivo = new File("./SimpleGrammarES2.txt");
        FileWriter fw = null;
        BufferedWriter bw = null;
        ArrayList<String> nombres = new ArrayList();
        try {
            fw = new FileWriter(archivo);
            bw = new BufferedWriter(fw);
            String texto = "#JSGF V1.0;\n"
                    + "grammar sentence;\n"
                    + " \n"
                    + "public <sentence> =\n"
                    + "[<dato0>]\n"
                    + "[<dato1>]\n"
                    + "[<dato2>]\n"
                    + "[<dato3>]\n"
                    + "[<dato4>]\n"
                    + "[<dato5>]\n"
                    + "[<dato6>]\n"
                    + "[<dato7>]\n"
                    + "[<dato8>]\n"
                    + "[<dato9>]\n"
                    + "[<dato10>]\n"
                    + "[<dato11>]\n"
                    + "[<dato12>]\n"
                    + "[<dato13>]";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from dbo.Contacto");
            int length = 13;
            while (rs.next()) {
                length++;
                nombres.add(rs.getString(2));
                texto += "\n[<dato" + length + ">]";
            }
            texto += "\n[<dato1><dato2><dato3><dato4><dato5><dato6><dato7><dato8><dato9><dato10><dato11><dato12><dato13>";
            for (int i = 14; i <= length; i++) {
                texto += "<dato" + i + ">";
            }
            texto += "];";
            texto += "<dato0>=Agregar;\n"
                    + "<dato1>=Modificar;\n"
                    + "<dato2>=User;\n"
                    + "<dato3>=Delete;\n"
                    + "<dato4>=Password;\n"
                    + "<dato5>=Call;\n"
                    + "<dato6>=Mensaje;\n"
                    + "<dato7>=Activar;\n"
                    + "<dato8>=Desactivar;\n"
                    + "<dato9>=Camara;\n"
                    + "<dato10>=Salir;\n"
                    + "<dato11>=Brian;\n"
                    + "<dato12>=Disco;\n"
                    + "<dato13>=Contacto;";
            for (int i = 1; i <= nombres.size(); i++) {
                texto += "<dato" + (i + 13) + ">=" + nombres.get(i - 1) + ";";
            }
            bw.write(texto);
            bw.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (Exception e) {
        }

    }


    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        this.jDialog1.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        this.jd_llamada.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

        try {
            if (!mic_activado) {
                mic_activado = true;
                recognizer.resume();
                recognizer.allocate();
                FileReader grammar1 = new FileReader("./SimpleGrammarES2.txt");

                RuleGrammar rg = recognizer.loadJSGF(grammar1);
                rg.setEnabled(true);

                recognizer.addResultListener(a);

                System.out.println("Empieze Dictado");
                recognizer.commitChanges();

                recognizer.requestFocus();

            } else {
                mic_activado = false;
                recognizer.pause();

                System.out.println("act: " + a.devolver);
                if (a.devolver.contains("User")) {
                    if (a.devolver.contains("Brian")) {
                        jt_username.setText("Brian");
                    }
                }

                if (a.devolver.contains("Password")) {
                    if (a.devolver.contains("Disco")) {
                        jt_password.setText("Disco");
                    }
                } else {
                    if (a.devolver.contains("Salir")) {
                        recognizer.deallocate();
                        JOptionPane.showMessageDialog(null, "Gracias por utilizar el programa!");
                        System.exit(0);

                    }
                }

                a.devolver = "";
                recognizer.removeResultListener(a);

            }
        } catch (Exception e) {
            System.out.println("Exception en " + e.toString());
            e.printStackTrace();
            System.exit(0);
        }

    }//GEN-LAST:event_jButton4MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        try {
            if (!mic_activado) {
                mic_activado = true;
                recognizer.resume();
                recognizer.allocate();
                FileReader grammar1 = new FileReader("./SimpleGrammarES2.txt");

                RuleGrammar rg = recognizer.loadJSGF(grammar1);
                rg.setEnabled(true);

                recognizer.addResultListener(a);

                System.out.println("Empieze Dictado");
                recognizer.commitChanges();

                recognizer.requestFocus();

            } else {
                mic_activado = false;
                recognizer.pause();

                System.out.println("act: " + a.devolver);

                if (a.devolver.equals("Agregar Contacto ")) {
                    jd_agregar.setModal(true);
                    jd_agregar.pack();
                    jd_agregar.setLocationRelativeTo(this);
                    jd_agregar.setVisible(true);
                }

                if (a.devolver.length() > 6) {
                    if (a.devolver.substring(0, 6).equals("Delete")) {
                        if (a.devolver.length() > 7) {
                            System.out.println(a.devolver.substring(7, a.devolver.length() - 1));
                        } else {
                            JOptionPane.showMessageDialog(this, "Comando No Válido");
                        }
                    }
                }
                if (a.devolver.length() > 9) {
                    if (a.devolver.substring(0, 9).equals("Modificar")) {
                        System.out.println("yeay");
                    }
                }
                if (a.devolver.equals("Salir ")) {
                    recognizer.deallocate();
                    JOptionPane.showMessageDialog(null, "Gracias por utilizar el programa!");
                    System.exit(0);

                }

                a.devolver = "";
                recognizer.removeResultListener(a);

            }
        } catch (Exception e) {
            System.out.println("Exception en " + e.toString());
            e.printStackTrace();
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            if (!mic_activado) {
                mic_activado = true;
                recognizer.resume();
                recognizer.allocate();
                FileReader grammar1 = new FileReader("./SimpleGrammarES2.txt");

                RuleGrammar rg = recognizer.loadJSGF(grammar1);
                rg.setEnabled(true);

                recognizer.addResultListener(a);

                System.out.println("Empieze Dictado");
                recognizer.commitChanges();

                recognizer.requestFocus();

            } else {
                mic_activado = false;
                recognizer.pause();

                System.out.println("act: " + a.devolver);
                if (a.devolver.contains("Agregar Contacto")) {
                    System.out.println("Agregar contacto");
                }

                if (a.devolver.contains("Delete")) {
                    System.out.println("Delete Contacto");
                }
                if (a.devolver.contains("Modificar")) {
                    System.out.println("Modificar Contacto");
                }
                if (a.devolver.contains("Salir")) {
                    recognizer.deallocate();
                    JOptionPane.showMessageDialog(null, "Gracias por utilizar el programa!");
                    System.exit(0);

                }

                a.devolver = "";
                recognizer.removeResultListener(a);

            }
        } catch (Exception e) {
            System.out.println("Exception en " + e.toString());
            e.printStackTrace();
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        try {
            if (!mic_activado) {
                mic_activado = true;
                recognizer.resume();
                recognizer.allocate();
                FileReader grammar1 = new FileReader("./SimpleGrammarES2.txt");

                RuleGrammar rg = recognizer.loadJSGF(grammar1);
                rg.setEnabled(true);

                recognizer.addResultListener(a);

                System.out.println("Empieze Dictado");
                recognizer.commitChanges();

                recognizer.requestFocus();

            } else {
                mic_activado = false;
                recognizer.pause();

                System.out.println("act: " + a.devolver);
                if (a.devolver.contains("Agregar Contacto")) {
                    System.out.println("Agregar contacto");
                }

                if (a.devolver.contains("Delete")) {
                    System.out.println("Delete Contacto");
                }
                if (a.devolver.contains("Modificar")) {
                    System.out.println("Modificar Contacto");
                }
                if (a.devolver.contains("Salir")) {
                    recognizer.deallocate();
                    JOptionPane.showMessageDialog(null, "Gracias por utilizar el programa!");
                    System.exit(0);

                }

                a.devolver = "";
                recognizer.removeResultListener(a);

            }
        } catch (Exception e) {
            System.out.println("Exception en " + e.toString());
            e.printStackTrace();
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(169, 145, 0);
            this.lb_foto.setIcon(new ImageIcon(img));
            path = archivo.getPath();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        try {

            if (!tf_telefono.getText().isEmpty()) {
                errores.setText("");
                Statement st = con.createStatement();
                String nombre = tf_nombre.getText();
                String telefono = tf_telefono.getText();
                String correo = tf_correo.getText();
                if (nombre.isEmpty()) {
                    nombre = "N/A";
                }
                st.execute("insert Contacto values ('" + nombre + "','" + telefono + "','" + correo + "','" + path + "')");
                JOptionPane.showMessageDialog(jd_agregar, "¡Contacto creado con exito!");
                tf_nombre.setText("");
                tf_telefono.setText("");
                tf_correo.setText("");
                Image img = Toolkit.getDefaultToolkit().createImage(getClass().getResource("user.png")).getScaledInstance(169, 145, 0);
                lb_foto.setIcon(new ImageIcon(img));
                jd_agregar.setVisible(false);
                this.setVisible(true);
                
               
            } else {
                JOptionPane.showMessageDialog(jd_agregar, "¡Ingrese un número de teléfono!");
                errores.setText("*");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        path = "user.png";
        refrescar_gramatica();


    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(false);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errores;
    private javax.swing.JLabel imagen_principal;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JDialog jd_llamada;
    private javax.swing.JPasswordField jt_password;
    private javax.swing.JTextField jt_username;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JTable tabla_contactos;
    private javax.swing.JTable tabla_llamadas;
    private javax.swing.JTable tabla_mensajes;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_telefono;
    // End of variables declaration//GEN-END:variables

}
